### ISSUE TITLE
Documentation invalid

### ISSUE THREAD

**Issue by pimjansen** [zendframework/ZendService_Twitter#19]
The documentation is not up to date and the examples are not working:
http://framework.zend.com/manual/2.2/en/modules/zendservice.twitter.html

Also there are `ZendRest\Client\Result` objects returned instead of the expected Twitter response objects as mentioned in the docs

`Every action you take returns a ZendService\Twitter\Twitter\Response object.`

**Comment by xyfantis** [comment]
:+1:

**Comment by weierophinney** [comment]
Please refer to the [README.md](https://github.com/zendframework/ZendService_Twitter/blob/master/README.md) for the most current documentation.
