### ISSUE TITLE
Media Entities missing in Status Show

### ISSUE THREAD

**Issue by ayacoo** [zendframework/ZendService_Twitter#36]
Twitter API removes entities if the tweet is truncated.
=> https://twittercommunity.com/t/media-entity-missing-from-entities-when-tweet-is-truncated-and-fetched-in-compatibility-mode/77321

statusesShow should support $query to set more parameters like "include_entities"

`$response = $this->get($path, array('include_entities' => true, 'tweet_mode' => 'extended'));`

**Comment by weierophinney** [comment]
These are present as of #37
